# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # Ruff - Fast Python linter and formatter (replaces Black, isort, flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        name: ruff-linter
      # Run the formatter
      - id: ruff-format
        name: ruff-formatter

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Prevent committing large files
      - id: check-added-large-files
        args: [--maxkb=1000]
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Check for merge conflict strings
      - id: check-merge-conflict
      # Check YAML file syntax
      - id: check-yaml
        exclude: ^\.github/
      # Check TOML file syntax
      - id: check-toml
      # Ensure files end with newline
      - id: end-of-file-fixer
        exclude: ^htmlcov/
      # Remove trailing whitespace
      - id: trailing-whitespace
        exclude: ^htmlcov/
      # Check for debugger imports
      - id: debug-statements

# Configuration
default_language_version:
  python: python3.13

# Only run on changed files
default_stages: [pre-commit]

# Run hooks in parallel when possible
fail_fast: false
